[workspace]
members = [
    "1/hello_cargo", "10/generic_type", "12/minigrep", "13/t_shirts",
    "2/guessing_game",
    "3/functions",
    "3/variables", "4/slice",
    "5/struct", "adder", "asdf",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies] 
